const initialBooks = [
  {
    id: 1,
    title: "My Little Brave Girl",
    author: "Hilary Duff ",
    genre: "Fiction",
    imageSrc: "/books/bravegirl.png",
    price: "$12",
  },
  {
    id: 2,
    title: "Good Egg",
    author: "Jory John",
    genre: "Fiction",
    imageSrc: "/books/goodegg.png",
    price: "$12",
  },
  {
    id: 3,
    title: "Hey Grandude!",
    author: "Paul McCartney",
    genre: "Classic",
    imageSrc: "/books/grandude.png",
    price: "$15",
  },
  {
    id: 4,
    title: "Just Because",
    author: "Matthew McConaughey",
    genre: "Fiction",
    imageSrc: "/books/justbecause.png",
    price: "$12",
  },
  {
    id: 5,
    title: "My Little Sweet Boy",
    author: "Hilary Duff ",
    genre: "Classic",
    imageSrc: "/books/sweetboy.png",
    price: "$15",
  },
  {
    id: 6,
    title: "My Little Brave Girl",
    author: "Hilary Duff ",
    genre: "Fiction",
    imageSrc: "/books/bravegirl.png",
    price: "$12",
  },
  {
    id: 7,
    title: "Just Because",
    author: "Matthew McConaughey",
    genre: "Fiction",
    imageSrc: "/books/justbecause.png",
    price: "$12",
  },
  {
    id: 8,
    title: "My Little Sweet Boy",
    author: "Hilary Duff ",
    genre: "Classic",
    imageSrc: "/books/sweetboy.png",
    price: "$15",
  },
  {
    id: 9,
    title: "My Little Brave Girl",
    author: "Hilary Duff ",
    genre: "Fiction",
    imageSrc: "/books/bravegirl.png",
    price: "$12",
  },
  {
    id: 10,
    title: "Dog Man: The Scarlet Shedder: A Graphic Novel  ",
    author: "Dav Pilkey",
    genre: "Classic",
    imageSrc: "/books/dogman.png",
    price: "$15",
  },
];

export default initialBooks;
